### PR TITLE
cut the number of times discovery restarts during testing

### PR DESCRIPTION
**Pull request by mgoldey**
- Collapses directory structure in examples
- Makes examples not overlap in entity names
- Only launches discovery once (except for intentional restarts)
- Ensure duplicate entity definitions are caught by pytest

### CODE REVIEW

**Review by cbrochtrup — APPROVED** [review]
This is a nice improvement. How much time do we save?

**Comment by mgoldey** [comment]
21% faster

**Comment by mgoldey** [comment]
or about 1 and a half minutes

**Comment by mgoldey** [comment]
This will require docs editing

**Comment by mgoldey** [comment]
updated https://github.com/finos/greenkey-discovery-sdk/wiki

**Pull request merged**
