### PR TITLE
remove usage of kwarg that does not exist before python 3.7

### PR DESCRIPTION
**Pull request by mgoldey**

### CODE REVIEW

**Comment by tshastry** [comment]
Do the logs look OK? I thought the text was required to get the right encoding....

**Comment by tshastry** [comment]
Ahh I see you are now decoding it.

**Review by tshastry — APPROVED** [review]

**Comment by mgoldey** [comment]
> Ahh I see you are now decoding it.

It didn't seem to require that but I put in the decode if the type somehow returns as the docs suggest it ought to

**Comment by mgoldey** [comment]
works on arbitrarily chosen python versions 3.5.9, 3.6.8, and 3.7.7

**Pull request merged**
